SCHEDULER_PREEMPTIVE_DEADLINE 50;
SLEEP_TIME 100;
SESSION_SIZE 4096;
CIRCLE_BUFFER_SIZE 51200;
MAX_PORTS 128;
REAL_TIME_DEAD_LINE 1;
REAL_TIME_USER_DEFINED 0;

TRUNK_ACCEPT_URI "udp://0.0.0.0:5060";
TRUNK_DISPATCH_URI "udp://10.0.0.1:5060";

my_custom_variable 42;
