SCHEDULER_PREEMPTIVE_DEADLINE 1;
SLEEP_TIME 10;
SESSION_SIZE 1024;
CIRCLE_BUFFER_SIZE 4096;
MAX_PORTS 20;
REAL_TIME_DEAD_LINE 2;
REAL_TIME_USER_DEFINED 18;
TRUNK_ACCEPT_URI "TCP/localhost:2727";
TRUNK_DISPATCH_URI "UDP/localhost:2727";